### ISSUE TITLE
死循环

### ISSUE THREAD

**Issue by jth445600** [rong6/Pikpak-Invitation#1]
![image](https://github.com/user-attachments/assets/31b0458c-8c6a-4e9c-87bc-19c830ca9487)
源码版和编译版都试了

**Comment by rong6** [comment]
将`invite_code.txt`删除重新输入，同时确保同目录下已有`mail.txt`文件并按格式放置邮箱密码。

**Comment by fireinrain** [comment]
> 将`invite_code.txt`删除重新输入，同时确保同目录下已有`mail.txt`文件并按格式放置邮箱密码。

我排查了一下 发现代码写的有点问题，在检查mail.txt，和再次读取mail.txt的过程中 不能直接return None，因为直接return None
又会进入到下一次循环，所以 这里比较好的方式是 改成 raise 一个exception  直接让外层的try except捕获。

另外  我个人尝试 貌似这个脚本 会一直触发captcha验证

**Comment by rong6** [comment]
> > 将`invite_code.txt`删除重新输入，同时确保同目录下已有`mail.txt`文件并按格式放置邮箱密码。
> 
> 我排查了一下 发现代码写的有点问题，在检查mail.txt，和再次读取mail.txt的过程中 不能直接return None，因为直接return None
> 又会进入到下一次循环，所以 这里比较好的方式是 改成 raise 一个exception  直接让外层的try except捕获。
> 
> 另外  我个人尝试 貌似这个脚本 会一直触发captcha验证


这玩意是随手借gpt的帮助改的，现在pikpak风控好像更严格了，没一个邀请成功的，所以我也不太想管了，如果可以你可以修改代码提个pr（）
